import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case japanese
    case english

    var id: String { rawValue }

    var resolvedLanguage: ResolvedAppLanguage {
        switch self {
        case .system:
            return Locale.preferredLanguages.first?.hasPrefix("ja") == true ? .japanese : .english
        case .japanese:
            return .japanese
        case .english:
            return .english
        }
    }

    func displayName(in language: ResolvedAppLanguage) -> String {
        switch self {
        case .system:
            return language == .japanese ? "自動" : "Automatic"
        case .japanese:
            return "日本語"
        case .english:
            return "English"
        }
    }
}

enum ResolvedAppLanguage: String {
    case japanese
    case english

    var localeIdentifier: String {
        switch self {
        case .japanese:
            return "ja_JP"
        case .english:
            return "en_US"
        }
    }
}

enum MemoriesLocalization {
    static func text(_ key: String, language: ResolvedAppLanguage) -> String {
        #if DEBUG
        let debugTable = language == .japanese ? debugJa : debugEn
        if let value = debugTable[key] {
            return value
        }
        #endif

        let table = language == .japanese ? ja : en
        return table[key] ?? en[key] ?? key
    }

    private static let ja: [String: String] = [
        "app.name": "Memories Pet Life",
        "common.ok": "OK",
        "common.close": "閉じる",
        "common.cancel": "キャンセル",
        "common.apply": "適用",
        "common.change": "変更",
        "common.loading": "読み込み中...",
        "common.unlimited": "無制限",
        "common.available": "未使用",
        "common.used": "使用済み",

        "home.tagline": "うちの子の今日を、おしゃれな思い出に",
        "home.choosePhoto": "写真・動画を選ぶ",
        "home.imageEditor": "写真・動画編集",
        "home.petCalendar": "うちの子カレンダー",
        "home.drafts": "下書き",
        "home.settings": "設定",
        "home.announcements": "お知らせ",
        "home.photoLoadFailed": "メディアを読み込めませんでした。別の写真または動画でもう一度お試しください。",
        "home.photoLoadError": "メディアの読み込みに失敗しました。時間をおいてもう一度お試しください。",
        "home.mediaLoadError": "メディアの読み込みに失敗しました。別の写真または動画でお試しください。",
        "style.ticketFrame": "チケット風フレーム",
        "style.ticketFrameDescription": "思い出をチケットのように残すデザイン",
        "style.simpleCard": "シンプルカードスタイル",
        "style.simpleCardDescription": "写真・動画に文字やアイコンを重ねる、すっきりしたデザイン",
        "style.retroFilm": "レトロフィルム風",
        "style.retroFilmDescription": "レトロ加工と日時表示で、懐かしい雰囲気に",
        "purchase.entry.title": "パスの購入",
        "purchase.entry.subtitle": "ウォーターマークなしで保存",
        "purchase.entry.cta": "パスを購入",

        "editor.title": "編集",
        "editor.saveDraft": "下書き保存",
        "editor.preview": "プレビュー",
        "editor.unsaved.title": "この編集内容を下書きに保存しますか？",
        "editor.unsaved.message": "下書き保存は明示操作のみです。",
        "editor.discard": "破棄して戻る",
        "editor.continue": "編集を続ける",
        "editor.savingDraft": "下書きを保存中...",
        "editor.draftSaved": "下書きに保存しました",
        "editor.draftSaveFailed": "下書き保存できませんでした",
        "editor.text": "文字",
        "editor.icon": "アイコン",
        "editor.appearance": "見た目",
        "editor.position": "配置",
        "editor.photo": "メディア",
        "editor.retroDateTime": "日時",
        "editor.retroFilter": "加工",
        "editor.retroDateHint": "写真・動画の右下に入る日時スタンプ",
        "editor.retroFilterHint": "レトロフィルム風の種類",
        "editor.retroStampPreview": "表示",
        "editor.textItems": "文字項目",
        "editor.main": "メイン",
        "editor.sub": "サブ",
        "editor.location": "場所",
        "editor.date": "日付",
        "editor.ticketTitle": "チケット名",
        "editor.ticketTitleHint": "MEMORY TICKETなど",
        "editor.ticketFixedStyle": "チケット風フレームは、文字色・フォント・配置が固定です。",
        "editor.mainText": "メインテキスト",
        "editor.subText": "サブテキスト",
        "editor.display": "表示",
        "editor.empty": "未入力",
        "editor.characterGuide": "%d / %d 文字まで",
        "editor.mainHint": "名前や、写真・動画のタイトル",
        "editor.subHint": "写真・動画の詳細",
        "editor.locationHint": "写真・動画の場所やシーン",
        "editor.dateHint": "写真・動画の日付や期間",
        "editor.mainPlaceholder": "My Pet / 今日の散歩 / Cafe Day",
        "editor.subPlaceholder": "犬種・猫種 / 年齢 / 今日のテーマ",
        "editor.locationPlaceholder": "Park / Cafe / Home",
        "editor.theme": "テーマ",
        "editor.weather": "天気",
        "editor.themeIcon": "テーマアイコン",
        "editor.weatherIcon": "天気アイコン",
        "retro.sepia": "セピア",
        "retro.nostalgic": "ノスタルジック",
        "retro.monochrome": "白黒",
        "editor.font": "フォント",
        "editor.color": "色",
        "editor.zoom": "拡大",
        "editor.adjustPhotoPosition": "写真・動画の位置を調整",
        "editor.dragPhotoHint": "プレビュー上でドラッグして位置、ピンチで拡大を調整できます",
        "editor.resetPhoto": "リセット",

        "date.select": "日付を選択",
        "date.edit": "日付を編集",
        "date.notApplied": "適用するまでカードには反映されません",
        "date.preview": "表示予定",
        "date.single": "1日",
        "date.range": "期間",
        "date.custom": "自由入力",
        "date.start": "開始日",
        "date.end": "終了日",
        "date.applied": "日付を反映しました",

        "preview.title": "プレビュー",
        "preview.creating": "プレビューを作成中...",
        "preview.processing": "処理中...",
        "preview.savePhoto": "写真アプリに保存",
        "preview.saveMedia": "写真アプリに保存",
        "preview.share": "共有する",
        "preview.backToEdit": "編集に戻る",
        "preview.watermark": "ウォーターマーク",
        "preview.withWatermark": "あり",
        "preview.withoutWatermark": "なし",
        "preview.withWatermarkFull": "ウォーターマークあり",
        "preview.withoutWatermarkFull": "ウォーターマークなし",
        "preview.withoutUnlimited": "パス有効",
        "preview.withoutOnce": "なしは1日1回",
        "preview.remainingToday": "本日あと%d回",
        "preview.todayAvailable": "本日あと1回",
        "preview.todayUsed": "本日分は使用済み",
        "preview.needMore": "パスなら無制限",
        "preview.viewPasses": "パスを購入",
        "preview.purchaseWithout": "パスを購入",
        "preview.lifetimeActive": "永久パス有効中",
        "preview.sevenDayActive": "7日間パス有効中",
        "preview.canSaveWithout": "ウォーターマークなし",
        "preview.activeUntil": "%@まで",
        "preview.confirmShareTitle": "ウォーターマークなしで共有しますか？",
        "preview.confirmShareMessage": "本日の無料分を使用します。",
        "preview.shareAction": "共有する",
        "preview.saveComplete": "保存が完了しました。",
        "preview.deleteDraft": "下書きを削除",
        "preview.keepDraft": "下書きを残す",
        "preview.saveDraft": "下書き保存",
        "preview.finishNoDraft": "残さず終了",
        "preview.returnToPreview": "プレビューに戻る",
        "preview.keepExistingDraftQuestion": "この下書きを残しますか？\n写真アプリに保存したメディアは残ります。",
        "preview.saveNewDraftQuestion": "この編集内容を下書きに保存しますか？\n保存しなくても、写真アプリに保存したメディアは残ります。",
        "preview.renderFailed": "プレビューを作成できませんでした",
        "preview.imageGenerateFailed": "画像の生成に失敗しました。",
        "preview.videoGenerateFailed": "動画の生成に失敗しました。",
        "preview.saveFailed": "保存できませんでした",
        "preview.shareFailed": "共有できませんでした",
        "preview.freeUsedTitle": "本日の無料枠を使用済みです",
        "preview.freeUsedMessage": "ウォーターマークあり保存は無制限で使えます。",
        "preview.freeUpdateFailed": "無料枠を更新できませんでした",
        "preview.draftDeleteFailed": "下書きを削除できませんでした",

        "calendar.title": "うちの子カレンダー",
        "calendar.tapDateInstruction": "日付をタップして写真や天気アイコンを登録できます。",
        "calendar.preview": "カレンダー出力",
        "calendar.help": "Widgetの使い方",
        "calendar.displayLanguage": "カレンダー表示",
        "calendar.choosePhoto": "写真を選ぶ",
        "calendar.adjustPhoto": "写真の位置を調整",
        "calendar.adjustPhotoHint": "ピンチで拡大、ドラッグで位置を調整できます。",
        "calendar.resetPhotoPlacement": "リセット",
        "calendar.overlay": "カレンダー表示",
        "calendar.themeIcon": "テーマアイコン",
        "calendar.weatherIcon": "天気アイコン",
        "calendar.position": "位置",
        "calendar.color": "色",
        "calendar.font": "フォント",
        "calendar.saveEntry": "登録する",
        "calendar.deleteEntry": "削除",
        "calendar.noPhoto": "写真または天気アイコンを選択してください。",
        "calendar.photoLoadFailed": "写真を読み込めませんでした。別の写真でもう一度お試しください。",
        "calendar.futureDate": "未来の日付には登録できません。",
        "calendar.replaceTitle": "既存の思い出を置き換えますか？",
        "calendar.replaceMessage": "この日にはすでに写真があります。置き換える場合だけ保存します。",
        "calendar.replace": "置き換える",
        "calendar.keepExisting": "既存のままにする",
        "calendar.photoDateMismatchTitle": "撮影日が違うようです",
        "calendar.photoDateMismatchMessage": "この写真の撮影日は %@ のようです。%@ に登録しますか？",
        "calendar.registerTargetDate": "%@に登録",
        "calendar.registerCapturedDate": "撮影日の%@に登録",
        "calendar.saved": "登録しました。",
        "calendar.saveFailed": "登録できませんでした。",
        "calendar.deleted": "削除しました。",
        "calendar.deleteConfirmTitle": "この日の記録を削除しますか？",
        "calendar.deleteConfirmMessage": "削除すると、この日の写真や表示設定は元に戻せません。",
        "calendar.saveCalendar": "カレンダーを保存",
        "calendar.shareCalendar": "カレンダーを共有",
        "calendar.withWatermark": "ウォーターマークあり",
        "calendar.withoutWatermark": "ウォーターマークなし",
        "calendar.outputTitle": "カレンダー出力",
        "calendar.outputSaved": "カレンダーを保存しました。",
        "calendar.outputSaveFailed": "カレンダーを保存できませんでした。",
        "calendar.outputShareFailed": "カレンダーを共有できませんでした。",
        "calendar.widgetHelpTitle": "Widgetの使い方",
        "calendar.widgetHelpHome": "ホーム画面Widgetでは、今月のうちの子カレンダーや今日の1枚を確認できます。",
        "calendar.widgetHelpAdd": "ホーム画面を長押しし、Widget追加画面から Memories Pet Life を選んで追加してください。",
        "calendar.widgetHelpTap": "Widgetをタップすると、うちの子カレンダーを開けます。",

        "drafts.title": "下書き",
        "drafts.empty": "下書きはまだありません",
        "drafts.untitled": "無題",
        "drafts.missingImage": "下書きメディアを読み込めませんでした",
        "drafts.delete": "削除",
        "drafts.deleteQuestion": "この下書きを削除しますか？",
        "drafts.full.title": "下書きがいっぱいです",
        "drafts.full.message": "下書きは最大%d件まで保存できます。",
        "drafts.fullBeforeEdit.message": "新しい編集はできますが、下書きとして保存するには整理が必要です。",
        "drafts.manage": "下書きを整理",

        "announcements.title": "お知らせ",
        "announcements.empty": "お知らせはまだありません",
        "announcements.markAllRead": "すべて既読にする",
        "announcements.unread": "未読",
        "announcements.loadFailed": "お知らせを取得できませんでした",
        "announcements.openURL": "詳細を見る",
        "announcements.refresh": "更新",

        "settings.title": "設定",
        "settings.version": "バージョン",
        "settings.language": "言語",
        "settings.privacy": "プライバシー",
        "settings.storage": "ストレージ",
        "settings.deleteTemporaryFiles": "一時ファイルを削除",
        "settings.deleteTemporaryFilesDescription": "編集中・書き出し中に作成された一時ファイルだけを削除します。保存済みの下書きは削除されません。",
        "settings.temporaryFilesDeleted": "一時ファイルを削除しました",
        "settings.temporaryFilesDeleteFailed": "一時ファイルを削除できませんでした",
        "settings.suggestPlaceFromPhotoLocation": "写真・動画の位置情報から場所を提案",
        "settings.suggestPlaceFromPhotoLocationDescription": "選択した写真または動画に位置情報が含まれる場合、場所欄の初期値に使用します。地名変換のために座標を利用する場合があります。",
        "settings.supportPolicies": "サポート・ポリシー",
        "settings.supportPage": "サポート",
        "settings.privacyPolicy": "プライバシーポリシー",
        "settings.legalDisclosure": "特定商取引法に基づく表記",
        "settings.plan": "プラン",
        "settings.free": "無料",
        "settings.sevenDayPass": "7日間パス",
        "settings.lifetimePass": "永久パス",
        "settings.planFree": "現在のプラン：無料",
        "settings.planSevenDay": "現在のプラン：7日間パス",
        "settings.planLifetime": "現在のプラン：永久パス",
        "settings.activeUntil": "%@ まで有効",
        "settings.canSaveWithout": "ウォーターマークなしで保存できます",
        "settings.todayFree": "本日のウォーターマークなし保存：%@",
        "settings.purchase": "パスを購入",
        "settings.restore": "購入を復元",

        "purchase.title": "パスの購入",
        "purchase.description": "ウォーターマークなし",
        "purchase.currentPlan.free": "現在のプラン：無料",
        "purchase.currentPlan.sevenDay": "現在のプラン：7日間パス",
        "purchase.currentPlan.lifetime": "現在のプラン：永久パス",
        "purchase.todayStatus": "本日分：%@",
        "purchase.remainingDays": "残り：あと%d日",
        "purchase.remainingOneDay": "残り：あと1日",
        "purchase.endsToday": "本日まで",
        "purchase.noWatermarkAvailable": "ウォーターマークなしで保存できます",
        "purchase.sevenDay.title": "7日間パス",
        "purchase.sevenDay.subtitle": "7日間、ウォーターマークなし",
        "purchase.sevenDay.detail": "",
        "purchase.lifetime.title": "永久パス",
        "purchase.lifetime.subtitle": "ずっとウォーターマークなし",
        "purchase.lifetime.detail": "",
        "purchase.purchase": "購入",
        "purchase.active": "適用中",
        "purchase.purchased": "購入済み",
        "purchase.restore": "購入を復元",
        "purchase.completed": "購入が完了しました",
        "purchase.failed": "購入できませんでした",
        "purchase.cancelled": "購入をキャンセルしました",
        "purchase.pending": "購入は保留中です",
        "purchase.productsFailed": "商品情報を取得できませんでした",
        "purchase.tryAgainLater": "時間をおいて再度お試しください",
        "purchase.unavailable": "—",
        "purchase.restored": "購入情報を復元しました",
        "purchase.noRestoredPurchases": "復元できる購入はありませんでした",
        "purchase.restoreFailed": "購入情報を復元できませんでした",
        "purchase.comingSoon": "商品情報を確認中です"
    ]

    private static let en: [String: String] = [
        "app.name": "Memories Pet Life",
        "common.ok": "OK",
        "common.close": "Close",
        "common.cancel": "Cancel",
        "common.apply": "Apply",
        "common.change": "Change",
        "common.loading": "Loading...",
        "common.unlimited": "Unlimited",
        "common.available": "Available",
        "common.used": "Used",

        "home.tagline": "Turn your pet's day into a beautiful memory",
        "home.choosePhoto": "Choose Photo / Video",
        "home.imageEditor": "Photo / Video Editor",
        "home.petCalendar": "Pet Calendar",
        "home.drafts": "Drafts",
        "home.settings": "Settings",
        "home.announcements": "Announcements",
        "home.photoLoadFailed": "Could not load this media. Please try another photo or video.",
        "home.photoLoadError": "Media loading failed. Please try again later.",
        "home.mediaLoadError": "Media loading failed. Please try another photo or video.",
        "style.ticketFrame": "Ticket Frame",
        "style.ticketFrameDescription": "A ticket-style design for saving a special memory.",
        "style.simpleCard": "Simple Card Style",
        "style.simpleCardDescription": "A clean design with text and icons over your photo or video.",
        "style.retroFilm": "Retro Film",
        "style.retroFilmDescription": "Apply a retro look and add a nostalgic date stamp.",
        "purchase.entry.title": "Buy Pass",
        "purchase.entry.subtitle": "Save without a watermark",
        "purchase.entry.cta": "Buy Pass",

        "editor.title": "Edit",
        "editor.saveDraft": "Save Draft",
        "editor.preview": "Preview",
        "editor.unsaved.title": "Save this edit as a draft?",
        "editor.unsaved.message": "Drafts are saved only when you choose to save them.",
        "editor.discard": "Discard and Go Back",
        "editor.continue": "Keep Editing",
        "editor.savingDraft": "Saving draft...",
        "editor.draftSaved": "Draft saved",
        "editor.draftSaveFailed": "Could not save draft",
        "editor.text": "Text",
        "editor.icon": "Icons",
        "editor.appearance": "Style",
        "editor.position": "Position",
        "editor.photo": "Media",
        "editor.retroDateTime": "Date",
        "editor.retroFilter": "Filter",
        "editor.retroDateHint": "Date stamp shown at the bottom right of the photo or video",
        "editor.retroFilterHint": "Choose a retro film filter",
        "editor.retroStampPreview": "Preview",
        "editor.textItems": "Text Items",
        "editor.main": "Main",
        "editor.sub": "Sub",
        "editor.location": "Location",
        "editor.date": "Date",
        "editor.ticketTitle": "Ticket",
        "editor.ticketTitleHint": "MEMORY TICKET, BIRTHDAY PASS, WALK TICKET, etc.",
        "editor.ticketFixedStyle": "Ticket Frame uses fixed font, color, and position.",
        "editor.mainText": "Main Text",
        "editor.subText": "Sub Text",
        "editor.display": "Show",
        "editor.empty": "Empty",
        "editor.characterGuide": "%d / %d chars max",
        "editor.mainHint": "Name or photo/video title",
        "editor.subHint": "Photo/video details",
        "editor.locationHint": "Photo/video place or scene",
        "editor.dateHint": "Photo/video date or period",
        "editor.mainPlaceholder": "My Pet / Morning Walk / Cafe Day",
        "editor.subPlaceholder": "Breed / age / today's theme",
        "editor.locationPlaceholder": "Park / Cafe / Home",
        "editor.theme": "Theme",
        "editor.weather": "Weather",
        "editor.themeIcon": "Theme Icon",
        "editor.weatherIcon": "Weather Icon",
        "retro.sepia": "Sepia",
        "retro.nostalgic": "Nostalgic",
        "retro.monochrome": "B&W",
        "editor.font": "Font",
        "editor.color": "Color",
        "editor.zoom": "Zoom",
        "editor.adjustPhotoPosition": "Adjust Photo / Video Position",
        "editor.dragPhotoHint": "Drag to adjust position, or pinch on the preview to zoom",
        "editor.resetPhoto": "Reset",

        "date.select": "Select Date",
        "date.edit": "Edit Date",
        "date.notApplied": "Changes appear after you apply them",
        "date.preview": "Preview",
        "date.single": "Single",
        "date.range": "Range",
        "date.custom": "Custom",
        "date.start": "Start Date",
        "date.end": "End Date",
        "date.applied": "Date applied",

        "preview.title": "Preview",
        "preview.creating": "Creating preview...",
        "preview.processing": "Processing...",
        "preview.savePhoto": "Save",
        "preview.saveMedia": "Save to Photos",
        "preview.share": "Share",
        "preview.backToEdit": "Back to Edit",
        "preview.watermark": "Watermark",
        "preview.withWatermark": "On",
        "preview.withoutWatermark": "Off",
        "preview.withWatermarkFull": "With watermark",
        "preview.withoutWatermarkFull": "Without watermark",
        "preview.withoutUnlimited": "Pass active",
        "preview.withoutOnce": "Off once/day",
        "preview.remainingToday": "%d left today",
        "preview.todayAvailable": "1 left today",
        "preview.todayUsed": "Used today",
        "preview.needMore": "Unlimited with pass",
        "preview.viewPasses": "Buy Pass",
        "preview.purchaseWithout": "Buy Pass",
        "preview.lifetimeActive": "Lifetime Pass active",
        "preview.sevenDayActive": "7-Day Pass active",
        "preview.canSaveWithout": "No watermark",
        "preview.activeUntil": "Until %@",
        "preview.confirmShareTitle": "Share without a watermark?",
        "preview.confirmShareMessage": "This uses today's free save.",
        "preview.shareAction": "Share",
        "preview.saveComplete": "Save complete.",
        "preview.deleteDraft": "Delete Draft",
        "preview.keepDraft": "Keep Draft",
        "preview.saveDraft": "Save Draft",
        "preview.finishNoDraft": "Finish Without Draft",
        "preview.returnToPreview": "Back to Preview",
        "preview.keepExistingDraftQuestion": "Keep this draft?\nThe saved media will remain in Photos.",
        "preview.saveNewDraftQuestion": "Save this edit as a draft?\nThe saved media will remain even without a draft.",
        "preview.renderFailed": "Could not create preview",
        "preview.imageGenerateFailed": "Image generation failed.",
        "preview.videoGenerateFailed": "Video generation failed.",
        "preview.saveFailed": "Could not save",
        "preview.shareFailed": "Could not share",
        "preview.freeUsedTitle": "Today's free save has been used",
        "preview.freeUsedMessage": "Saving with a watermark is unlimited.",
        "preview.freeUpdateFailed": "Could not update free save",
        "preview.draftDeleteFailed": "Could not delete draft",

        "calendar.title": "Pet Calendar",
        "calendar.tapDateInstruction": "Tap a date to add a photo or weather icon.",
        "calendar.preview": "Calendar Export",
        "calendar.help": "How to Use Widgets",
        "calendar.displayLanguage": "Calendar Display",
        "calendar.choosePhoto": "Choose Photo",
        "calendar.adjustPhoto": "Adjust Photo Position",
        "calendar.adjustPhotoHint": "Pinch to zoom and drag to position the photo.",
        "calendar.resetPhotoPlacement": "Reset",
        "calendar.overlay": "Calendar Marks",
        "calendar.themeIcon": "Theme Icon",
        "calendar.weatherIcon": "Weather Icon",
        "calendar.position": "Position",
        "calendar.color": "Color",
        "calendar.font": "Font",
        "calendar.saveEntry": "Add",
        "calendar.deleteEntry": "Delete",
        "calendar.noPhoto": "Please choose a photo or weather icon.",
        "calendar.photoLoadFailed": "Could not load this photo. Please try another one.",
        "calendar.futureDate": "Future dates cannot be registered.",
        "calendar.replaceTitle": "Replace existing memory?",
        "calendar.replaceMessage": "This date already has a photo. Save only if you want to replace it.",
        "calendar.replace": "Replace",
        "calendar.keepExisting": "Keep Existing",
        "calendar.photoDateMismatchTitle": "Photo Date Looks Different",
        "calendar.photoDateMismatchMessage": "This photo seems to have been taken on %@. Register it on %@?",
        "calendar.registerTargetDate": "Register on %@",
        "calendar.registerCapturedDate": "Use %@",
        "calendar.saved": "Saved.",
        "calendar.saveFailed": "Could not save.",
        "calendar.deleted": "Deleted.",
        "calendar.deleteConfirmTitle": "Delete this memory?",
        "calendar.deleteConfirmMessage": "This will remove the photo and display settings for this day.",
        "calendar.saveCalendar": "Save Calendar",
        "calendar.shareCalendar": "Share Calendar",
        "calendar.withWatermark": "With Watermark",
        "calendar.withoutWatermark": "Without Watermark",
        "calendar.outputTitle": "Calendar Export",
        "calendar.outputSaved": "Calendar saved.",
        "calendar.outputSaveFailed": "Could not save calendar.",
        "calendar.outputShareFailed": "Could not share calendar.",
        "calendar.widgetHelpTitle": "How to Use Widgets",
        "calendar.widgetHelpHome": "Home Screen widgets can show this month's pet calendar or today's photo.",
        "calendar.widgetHelpAdd": "Touch and hold the Home Screen, open the widget picker, and choose Memories Pet Life.",
        "calendar.widgetHelpTap": "Tap a widget to open Pet Calendar.",

        "drafts.title": "Drafts",
        "drafts.empty": "No drafts yet",
        "drafts.untitled": "Untitled",
        "drafts.missingImage": "Could not load draft media",
        "drafts.delete": "Delete",
        "drafts.deleteQuestion": "Delete this draft?",
        "drafts.full.title": "Drafts are full",
        "drafts.full.message": "You can save up to %d drafts.",
        "drafts.fullBeforeEdit.message": "You can keep editing, but you’ll need to delete a draft before saving a new one.",
        "drafts.manage": "Manage Drafts",

        "announcements.title": "Announcements",
        "announcements.empty": "No announcements yet",
        "announcements.markAllRead": "Mark All as Read",
        "announcements.unread": "Unread",
        "announcements.loadFailed": "Could not load announcements",
        "announcements.openURL": "Learn More",
        "announcements.refresh": "Refresh",

        "settings.title": "Settings",
        "settings.version": "Version",
        "settings.language": "Language",
        "settings.privacy": "Privacy",
        "settings.storage": "Storage",
        "settings.deleteTemporaryFiles": "Delete Temporary Files",
        "settings.deleteTemporaryFilesDescription": "Deletes only temporary editing and export files. Saved drafts are not deleted.",
        "settings.temporaryFilesDeleted": "Temporary files deleted",
        "settings.temporaryFilesDeleteFailed": "Could not delete temporary files",
        "settings.suggestPlaceFromPhotoLocation": "Suggest place from photo/video location",
        "settings.suggestPlaceFromPhotoLocationDescription": "When a selected photo or video includes location data, it can be used to suggest the initial place text. Coordinates may be used for place name lookup.",
        "settings.supportPolicies": "Support & Policies",
        "settings.supportPage": "Support",
        "settings.privacyPolicy": "Privacy Policy",
        "settings.legalDisclosure": "Legal Disclosure",
        "settings.plan": "Plan",
        "settings.free": "Free",
        "settings.sevenDayPass": "7-Day Pass",
        "settings.lifetimePass": "Lifetime Pass",
        "settings.planFree": "Current Plan: Free",
        "settings.planSevenDay": "Current Plan: 7-Day Pass",
        "settings.planLifetime": "Current Plan: Lifetime Pass",
        "settings.activeUntil": "Active until %@",
        "settings.canSaveWithout": "You can save without a watermark",
        "settings.todayFree": "Today's watermark-free save: %@",
        "settings.purchase": "Buy Pass",
        "settings.restore": "Restore purchases",

        "purchase.title": "Buy Pass",
        "purchase.description": "No watermark",
        "purchase.currentPlan.free": "Current Plan: Free",
        "purchase.currentPlan.sevenDay": "Current Plan: 7-Day Pass",
        "purchase.currentPlan.lifetime": "Current Plan: Lifetime Pass",
        "purchase.todayStatus": "Today: %@",
        "purchase.remainingDays": "Remaining: %d days",
        "purchase.remainingOneDay": "Remaining: 1 day",
        "purchase.endsToday": "Ends today",
        "purchase.noWatermarkAvailable": "You can save without a watermark",
        "purchase.sevenDay.title": "7-Day Pass",
        "purchase.sevenDay.subtitle": "No watermark for 7 days",
        "purchase.sevenDay.detail": "",
        "purchase.lifetime.title": "Lifetime Pass",
        "purchase.lifetime.subtitle": "No watermark forever",
        "purchase.lifetime.detail": "",
        "purchase.purchase": "Purchase",
        "purchase.active": "Active",
        "purchase.purchased": "Purchased",
        "purchase.restore": "Restore",
        "purchase.completed": "Purchase completed",
        "purchase.failed": "Purchase failed",
        "purchase.cancelled": "Purchase cancelled",
        "purchase.pending": "Purchase pending",
        "purchase.productsFailed": "Products could not be loaded",
        "purchase.tryAgainLater": "Please try again later",
        "purchase.unavailable": "—",
        "purchase.restored": "Purchases restored",
        "purchase.noRestoredPurchases": "No purchases to restore",
        "purchase.restoreFailed": "Could not restore purchases",
        "purchase.comingSoon": "Checking product information"
    ]

    #if DEBUG
    private static let debugJa: [String: String] = [
        "settings.debug": "DEBUG",
        "settings.resetFree": "ウォーターマークなし無料枠をリセット",
        "settings.resetFreeDescription": "本日の無料分を未使用状態に戻します。Releaseビルドには表示されません。",
        "settings.resetFreeDone": "ウォーターマークなし無料枠をリセットしました",
        "settings.currentRemaining": "現在: 本日あと%d回",
        "settings.currentUsed": "現在: 本日分を使用済み",
        "settings.debugEntitlement": "有料状態を切り替え",
        "settings.debugDraftLimit": "下書き上限",
        "debug.real": "実状態を使う",
        "debug.free": "無料",
        "debug.freeUsedToday": "無料・本日分使用済み",
        "debug.sevenDayActive": "7日間パス有効",
        "debug.sevenDayExpired": "7日間パス期限切れ",
        "debug.lifetime": "永久パス有効",
        "debug.draftLimit.real": "実上限を使う",
        "debug.draftLimit.one": "1件",
        "debug.draftLimit.two": "2件",
        "debug.draftLimit.five": "5件",
        "debug.draftLimit.ten": "10件",
        "debug.draftLimit.hundred": "100件"
    ]

    private static let debugEn: [String: String] = [
        "settings.debug": "DEBUG",
        "settings.resetFree": "Reset watermark-free save",
        "settings.resetFreeDescription": "Resets today's free save. This is hidden in Release builds.",
        "settings.resetFreeDone": "Watermark-free save reset",
        "settings.currentRemaining": "Current: %d remaining today",
        "settings.currentUsed": "Current: used today",
        "settings.debugEntitlement": "Debug entitlement",
        "settings.debugDraftLimit": "Draft limit",
        "debug.real": "Use real state",
        "debug.free": "Free",
        "debug.freeUsedToday": "Free, used today",
        "debug.sevenDayActive": "7-Day Pass active",
        "debug.sevenDayExpired": "7-Day Pass expired",
        "debug.lifetime": "Lifetime Pass active",
        "debug.draftLimit.real": "Use real limit",
        "debug.draftLimit.one": "1",
        "debug.draftLimit.two": "2",
        "debug.draftLimit.five": "5",
        "debug.draftLimit.ten": "10",
        "debug.draftLimit.hundred": "100"
    ]
    #endif
}
